.github/workflows/github-action.yml
- resolve #3 
- Github Action & Slack 연동
<br>
- `.github/workflows/fithub-action.yaml` 파일 수정
- `action-slack` 앱과 `Github Action` 연동하는 스크립트 추가
<br>
- `.github/workflows/fithub-action.yaml` 파일을 수정했습니다.
- ~기존 workflow를 해치지 않는지, 그리고 슬랙 알림이 잘 작동하는지 테스트가 필요합니다.~
- ~테스트 위해 main 브랜치에 merge 필요~
- `merge` 안했는데도 잘 작동함 🤔
<br>
=> [SETTING] Github Action & Slack 연동

.gitignore, build.gradle, src/main/java/com/prgrms/team03linkbookbe/bookmark/entity/Bookmark.java, src/main/java/com/prgrms/team03linkbookbe/bookmark/repository/BookMarkRepository.java, src/main/java/com/prgrms/team03linkbookbe/comment/entity/Comment.java, src/main/java/com/prgrms/team03linkbookbe/comment/repository/CommentRepository.java, src/main/java/com/prgrms/team03linkbookbe/common/entity/BaseDateEntity.java, src/main/java/com/prgrms/team03linkbookbe/config/JpaAuditConfiguration.java, src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java, src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java, src/main/java/com/prgrms/team03linkbookbe/hashtag/entity/Field.java, src/main/java/com/prgrms/team03linkbookbe/hashtag/entity/Hashtag.java, src/main/java/com/prgrms/team03linkbookbe/hashtag/repository/HashtagRepository.java, src/main/java/com/prgrms/team03linkbookbe/interest/entity/Field.java, src/main/java/com/prgrms/team03linkbookbe/interest/entity/Interest.java, src/main/java/com/prgrms/team03linkbookbe/interest/repository/InterestRepository.java, src/main/java/com/prgrms/team03linkbookbe/like/entity/Like.java, src/main/java/com/prgrms/team03linkbookbe/like/repository/LikeRepository.java, src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java, src/main/java/com/prgrms/team03linkbookbe/user/repository/UserRepository.java
- resolve #7 
<br>
entity class 구현
=> [FEAT] entity class 구현

build.gradle
- resolve #10 
- 테스트 커버리지 측정 플로우 도입
<br>
> 라이브러리 이름 및 버전
- [JaCoCo (Java Code Coverage Library)](https://www.eclemma.org/jacoco/)
> 환경파일 세팅 방법
- `build.gradle` 파일에 dependency 추가
<br>
=> [SETTING] 테스트 커버리지 측정 Flow 도입

src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java, src/main/java/com/prgrms/team03linkbookbe/common/exception/GlobalExceptionHandler.java, src/main/java/com/prgrms/team03linkbookbe/common/exception/NoDataException.java, src/main/java/com/prgrms/team03linkbookbe/common/response/ExceptionResponse.java
- resolve #{issue_number}
<br>
Exception Response class 구현
=> [FEAT] Exception Response class 구현

build.gradle, src/main/java/com/prgrms/team03linkbookbe/comment/dto/CommentResponseDto.java, src/main/java/com/prgrms/team03linkbookbe/comment/dto/CreateCommentRequestDto.java, src/main/java/com/prgrms/team03linkbookbe/comment/dto/CreateCommentResponseDto.java, src/main/java/com/prgrms/team03linkbookbe/comment/dto/UpdateCommentRequestDto.java, src/main/java/com/prgrms/team03linkbookbe/comment/dto/UpdateCommentResponseDto.java, src/main/java/com/prgrms/team03linkbookbe/comment/entity/Comment.java, src/main/java/com/prgrms/team03linkbookbe/comment/repository/CommentRepository.java, src/main/java/com/prgrms/team03linkbookbe/comment/service/CommentService.java, src/main/java/com/prgrms/team03linkbookbe/common/entity/BaseDateEntity.java, src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java, src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java, src/test/java/com/prgrms/team03linkbookbe/unit/comment/repository/CommentRepositoryTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/comment/service/CommentServiceTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/repository/CommentRepositoryTest.java
- resolve #17
- 댓글 CRUD 레포지터리 & 테스트 구현
<br>
- 댓글, 폴더, 유저 엔티티 간의 연관관계 설정을 했습니다.
<br>
=> [FEAT] 댓글 CRUD 레포지터리 & 테스트 구현

.github/workflows/github-action.yml, src/main/java/com/prgrms/team03linkbookbe/bookmark/dto/BookmarkResponse.java, src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java, src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/CreateFolderRequest.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderIdResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderListResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java, src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java, src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java, src/main/java/com/prgrms/team03linkbookbe/folderTag/entity/FolderTag.java, src/main/java/com/prgrms/team03linkbookbe/folderTag/repository/FolderTagRepository.java, src/main/java/com/prgrms/team03linkbookbe/hashtag/entity/Field.java, src/main/java/com/prgrms/team03linkbookbe/hashtag/repository/HashtagRepository.java, src/main/java/com/prgrms/team03linkbookbe/like/repository/LikeRepository.java, src/main/java/com/prgrms/team03linkbookbe/tag/entity/Tag.java, src/main/java/com/prgrms/team03linkbookbe/tag/entity/TagCategory.java, src/main/java/com/prgrms/team03linkbookbe/tag/repository/TagRepository.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/UserResponse.java, src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java
-  issue 11
- 폴더 CRUD
<br>
- 전체적으로 어색한부분이 없는지 가볍게만 봐주시면 감사하겠습니다 (컨벤션정도) 아직 테스트 진행을 하지 못해서 PR point는 딱히 없습니다!
<br>
=> [FEAT] 폴더 CRUD

src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java, src/main/java/com/prgrms/team03linkbookbe/tag/entity/Tag.java
=> 🐛폴더 태그 연관관계매핑 수정 및 해결

src/main/java/com/prgrms/team03linkbookbe/bookmark/controller/BookmarkController.java, src/main/java/com/prgrms/team03linkbookbe/bookmark/dto/BookmarkIdResponse.java, src/main/java/com/prgrms/team03linkbookbe/bookmark/dto/BookmarkRequest.java, src/main/java/com/prgrms/team03linkbookbe/bookmark/entity/Bookmark.java, src/main/java/com/prgrms/team03linkbookbe/bookmark/service/BookmarkService.java, src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java, src/main/java/com/prgrms/team03linkbookbe/like/repository/LikeRepository.java
- 북마크 CRUD 코드구현 
- Folder 좋아요 수 세기 로직 개선 
<br>
- 북마크 CRUD코드 작성했습니다. 북마크의 경우 생성, 수정, 삭제의 경우에 해당 폴더로 페이지가 리다이렉트 될 것같은데 이 정보는 이미 프론트에서 가지고있기때문에 북마크 id를 반환해줄필요가 없을 것같아서 모두 void로 작성했습니다. void로 리턴값할때 상태코드만 주려고 ResponseEntity없이 controller에서  `@ResponseStatus(HttpStatus.OK)`만 붙여줬는데 response body가 없을때 다들 어떻게 처리하시는지 궁금하네요~🧐🧐
<br>
=> [FEAT] 북마크 CRUD

src/main/java/com/prgrms/team03linkbookbe/bookmark/controller/BookmarkController.java, src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java, src/test/java/com/prgrms/team03linkbookbe/integration/comment/CommentIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/comment/repository/CommentRepositoryTest.java
- resolve #35 
- EC2 build 실패 오류 해결
- DB 맵핑 실패-1 (notNull / Nullable)
- DB 맵핑 실패-2 (Column 맵핑 안됨)
- `application-jwt.yaml` 파일 부재
- Ambiguous API 오류 (`@PutMapping` → `@DeleteMapping` 으로 수정)
- 실패하는 테스트 Disable 처리
<br>
- 위에 기재한 부분 관련 코드 수정
- 정상 빌드 확인 완료
- 발생하는 빌드 warnings 들 까지 수정해 주었습니다.
=> [BUG] EC2 build 실패 오류 해결 (Hotfix)

src/main/java/com/prgrms/team03linkbookbe/bookmark/controller/BookmarkController.java, src/main/java/com/prgrms/team03linkbookbe/interest/dto/InterestDto.java, src/main/java/com/prgrms/team03linkbookbe/interest/entity/Field.java, src/main/java/com/prgrms/team03linkbookbe/interest/entity/Interest.java, src/main/java/com/prgrms/team03linkbookbe/refreshtoken/dto/AccessTokenResponseDto.java, src/main/java/com/prgrms/team03linkbookbe/refreshtoken/entity/RefreshToken.java, src/main/java/com/prgrms/team03linkbookbe/refreshtoken/service/RefreshTokenService.java, src/main/java/com/prgrms/team03linkbookbe/user/controller/UserController.java, src/main/java/com/prgrms/team03linkbookbe/user/controller/UserControllerAdvice.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/LoginResponseDto.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/RegisterRequestDto.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/UpdateRequestDto.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/UserLoginResponseDto.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/UserResponse.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/UserResponseDto.java, src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java, src/main/java/com/prgrms/team03linkbookbe/user/repository/UserRepository.java, src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java, src/test/java/com/prgrms/team03linkbookbe/unit/user/repository/UserRepositoryTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
- resolve #32 
<br>
User Repository, Service Test 구현, User 로그인 수정
- 리뷰어가 참고할만한 사항이 있으면 적어주세요.                              
<br>
- 이메일, 비밀번호 로그인 시에
그리고 RefreshToken으로 AccessToken 재발급 시에
UserDetail 정보를 Token 과 같이 던져줍니다.
- 이메일, 비밀번호 첫로그인을 판별하기 위해 IsFirstLogin field를 Dto에 추가해 주 었습니다.
- Postman으로 User update test 했었는데 정상적으로 작동이 안되네요.. 이부분 추가 수정해서 이후에 PR 올리겠습니다.
=> :recycle: User Repository, Service Test 구현, User 로그인 수정

src/main/java/com/prgrms/team03linkbookbe/user/controller/UserController.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/UserLoginResponseDto.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/UserUpdateRequestDto.java, src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java, src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java, src/test/java/com/prgrms/team03linkbookbe/integration/refreshtoken/RefreshTokenIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/user/controller/UserControllerUnitTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
- resolve #41 
- RefreshToken 통합 테스트 작성
<br>
- RefreshToken 통합 테스트 작성
<br>
=> [FEAT] RefreshToken 통합 테스트 작성

src/main/java/com/prgrms/team03linkbookbe/comment/service/CommentService.java, src/main/java/com/prgrms/team03linkbookbe/like/service/LikeService.java, src/test/java/com/prgrms/team03linkbookbe/unit/comment/service/CommentServiceTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/like/service/LikeServiceTest.java
- resolve #44 
- 댓글, 좋아요 테스트 오류 해결
- 유저 인증을 findById에서 findByEmail로 변경
=> [bug] 댓글, 좋아요 테스트 오류 수정

src/test/java/com/prgrms/team03linkbookbe/integration/comment/CommentIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/integration/like/LikeIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/comment/service/CommentServiceTest.java
- resolve #44
- 댓글, 좋아요 테스트 오류 해결
- 통합 테스트 부분 전부 주석 처리
=> :bug:댓글, 좋아요 테스트 오류 수정

src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java
- resolve #48 
- 인증, 인가 필요 없는 API 설정 추가
<br>
- Folder, Comment 엔터티는 Get 모두 허용으로 변경했습니다.
<br>
=> [FEAT] 인증, 인가 필요 없는 API 설정 추가

src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java
- resolve #51 
- Like get 모두 허용
<br>
- Like get 모두 허용으로 변경
<br>
=> [REFACTOR] Like Get 모두 허용으로 변경

build.gradle, src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java, src/main/java/com/prgrms/team03linkbookbe/interest/dto/InterestDto.java, src/main/java/com/prgrms/team03linkbookbe/interest/entity/Field.java, src/main/java/com/prgrms/team03linkbookbe/interest/entity/Interest.java, src/main/java/com/prgrms/team03linkbookbe/jwt/Jwt.java, src/main/java/com/prgrms/team03linkbookbe/refreshtoken/controller/RefreshTokenController.java, src/main/java/com/prgrms/team03linkbookbe/refreshtoken/service/RefreshTokenService.java, src/main/java/com/prgrms/team03linkbookbe/user/controller/UserController.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/UserDetailResponseDto.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/UserUpdateRequestDto.java, src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java, src/main/java/com/prgrms/team03linkbookbe/user/repository/UserRepository.java, src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java, src/test/java/com/prgrms/team03linkbookbe/integration/refreshtoken/RefreshTokenIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/refreshtoken/repository/RefreshTokenRepositoryTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/refreshtoken/service/RefreshTokenServiceTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
- resolve #49
<br>
RefreshToken Repository, Service Test 구현, User update 로직 수정
=> RefreshToken Repository, Service Test 구현, User update 로직 수정

src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java
- resolve #55 
- CORS 모두 허용 추가
<br>
=> [FEAT] CORS 모두 허용 추가

src/main/java/com/prgrms/team03linkbookbe/comment/dto/UpdateCommentRequest.java
- resolve #59 
- 댓글 업데이트 부분 수정
<br>
- 수정 시 수정이 아닌 추가가 되는 문제를 해결
<br>
=> [REFACTOR] 댓글 수정 부분 수정

src/main/java/com/prgrms/team03linkbookbe/bookmark/repository/BookmarkRepository.java, src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/RegisterRequestDto.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/UserDetailResponseDto.java, src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java, src/test/java/com/prgrms/team03linkbookbe/integration/refreshtoken/RefreshTokenIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/integration/user/UserIntegrationTest.java
- resolve #53 
- User 통합 테스트 작성
<br>
- User 통합 테스트 작성
- ILLEGAL_TOKEN 에러 메시지 수정 -> "비정상적인 접근입니다."
- 회원가입 요청 시 request dto에 email 추가 & email nullable false로 변경
- dto from entity에 id 누락 수정
<br>
=> [FEAT] User 통합 테스트 작성

src/main/java/com/prgrms/team03linkbookbe/comment/controller/CommentController.java, src/main/java/com/prgrms/team03linkbookbe/comment/dto/CreateCommentRequest.java, src/main/java/com/prgrms/team03linkbookbe/comment/service/CommentService.java, src/test/java/com/prgrms/team03linkbookbe/unit/comment/controller/CommentControllerTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/comment/service/CommentServiceTest.java
=> [bug] 댓글 부분 오류 수정

src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java
- resolve #70 
- cors 에러
<br>
- preflight 열어줬는데 이걸로 해결될지 모르겠습니다.
<br>
=> :bug: cors preflight 허용 추가

.gitignore, src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java, src/main/java/com/prgrms/team03linkbookbe/config/EmailConfig.java, src/main/java/com/prgrms/team03linkbookbe/config/WebSecurityConfigure.java, src/main/java/com/prgrms/team03linkbookbe/email/controller/EmailController.java, src/main/java/com/prgrms/team03linkbookbe/email/controller/EmailControllerAdvice.java, src/main/java/com/prgrms/team03linkbookbe/email/dto/EmailCertificationRequestDto.java, src/main/java/com/prgrms/team03linkbookbe/email/dto/EmailRequestDto.java, src/main/java/com/prgrms/team03linkbookbe/email/exception/EmailCertificationFailureException.java, src/main/java/com/prgrms/team03linkbookbe/email/exception/EmailSendFailureException.java, src/main/java/com/prgrms/team03linkbookbe/email/service/EmailService.java, src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java, src/main/resources/application.yaml, src/test/java/com/prgrms/team03linkbookbe/integration/email/EmailIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/email/controller/EmailControllerUnitTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/email/service/EmailServiceTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java, src/test/resources/application.yaml
- resolve #{67}
이메일 인증 기능 구현
<br>
=> [feat] 이메일 인증 기능 구현

src/main/java/com/prgrms/team03linkbookbe/comment/service/CommentService.java, src/main/java/com/prgrms/team03linkbookbe/like/service/LikeService.java, src/test/java/com/prgrms/team03linkbookbe/unit/like/service/LikeServiceTest.java
- resolve #69 
- 좋아요 + 댓글 Serivce 유효성 검사 추가
<br>
- 서비스에 유효성 관련 코드 추가
<br>
- 리뷰어가 참고할만한 사항이 있으면 적어주세요.                              
<br>
=> [REFACTOR] 좋아요 + 댓글 Serivce 유효성 검사 추가

src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java, src/main/java/com/prgrms/team03linkbookbe/email/exception/EmailIsNotCertificatedException.java, src/main/java/com/prgrms/team03linkbookbe/email/service/EmailService.java, src/main/java/com/prgrms/team03linkbookbe/user/controller/UserController.java, src/main/java/com/prgrms/team03linkbookbe/user/controller/UserControllerAdvice.java, src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java, src/test/java/com/prgrms/team03linkbookbe/integration/email/EmailIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/integration/user/UserIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/email/controller/EmailControllerUnitTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/email/service/EmailServiceTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/user/controller/UserControllerUnitTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
- resolve #{77}
회원가입 시에 인증 이메일 검증 추가 
<br>
- 추가 또는 변경된 내용을 적어주세요. 
<br>
- 리뷰어가 참고할만한 사항이 있으면 적어주세요.                              
<br>
=> [FEAT] 회원가입 시에 인증 이메일 검증 추가 

src/main/java/com/prgrms/team03linkbookbe/rootTag/entity/RootTagCategory.java
- 태그이름수정
- DB 반영
- 매핑함수추가
<br>
=> [feat] 태그 추가 기능개발

src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java, src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java, src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
- resolve #76 
- 제목으로 검색
<br>
- 줄바꿈이 맘대로 되어버렸네요 😅
- 폴더쪽 api로 추가했습니다!
<br>
=> :sparkles:[FEAT] 폴더 제목으로 검색 기능 개발

.gitignore, src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderListResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/RootTagRequest.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/TagRequest.java, src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java, src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java, src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java, src/main/java/com/prgrms/team03linkbookbe/folderTag/repository/FolderTagRepository.java, src/main/java/com/prgrms/team03linkbookbe/tag/repository/TagRepository.java
- resolve #75 
- 루트 태그, 태그로 검색기능 추가
<br>
- 루트 태그, 태그로 검색기능 추가
<br>
=> [FEAT] 루트 태그, 태그로 검색기능 추가

.gitignore, src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderListByUserResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderListResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java, src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java, src/main/java/com/prgrms/team03linkbookbe/like/dto/LikeResponse.java, src/main/java/com/prgrms/team03linkbookbe/like/service/LikeService.java
- resolve #68 
- 좋아요한 폴더 표시 추가
=> ♻️[REFECTOR] 좋아요한 폴더 표시 추가

src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java, src/main/java/com/prgrms/team03linkbookbe/folderTag/repository/FolderTagRepository.java
- resolve #84 
- Folder 쿼리 DISTINCT 추가
<br>
- Folder 쿼리 DISTINCT 추가
<br>
=> [REFACTOR] Folder 쿼리 DISTINCT 추가

src/main/java/com/prgrms/team03linkbookbe/like/controller/LikeController.java, src/main/java/com/prgrms/team03linkbookbe/like/service/LikeService.java, src/test/java/com/prgrms/team03linkbookbe/integration/like/LikeIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/like/controller/LikeControllerTest.java
- resolve #87 
- 좋아요 통합 테스트 개발
<br>
=> :sparkles:[FEAT] 좋아요 부분 통합테스트 개발

src/main/java/com/prgrms/team03linkbookbe/comment/controller/CommentController.java, src/test/java/com/prgrms/team03linkbookbe/integration/comment/CommentIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/comment/controller/CommentControllerTest.java
- resolve #86 
- 댓글 부분 통합테스트 개발
<br>
=> :sparkles:[FEAT] 댓글 부분 통합테스트 개발

src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/OriginFolderResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/OriginUserResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
- resolve #95 
- 폴더 세부조회 시 원본폴더 정보 보기 구현.
<br>
=> :sparkles:[FEAT] 폴더 세부조회 시 원본폴더 정보 보기 구현

src/main/java/com/prgrms/team03linkbookbe/folder/dto/CreateFolderRequest.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/RootTagRequest.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/TagRequest.java, src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java, src/test/java/com/prgrms/team03linkbookbe/unit/folder/repository/FolderRepositoryUnitTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/folder/service/FolderServiceUnitTest.java
- resolve #93 
- 폴더 서비스, 레파지토리 단위 테스트 작성
<br>
- 폴더 서비스, 레파지토리 단위 테스트 작성
<br>
=> [FEAT] 폴더 서비스, 레파지토리 단위 테스트 작성

src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
- resolve #100 
- 폴더 수정 삭제 생성 통합테스트 구현
<br>
=> :sparkles:[FEAT] 폴더 수정 삭제 생성 통합테스트 구현

src/main/java/com/prgrms/team03linkbookbe/rootTag/entity/RootTag.java, src/test/java/com/prgrms/team03linkbookbe/integration/bookmark/BookmarkIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
=> [test] 북마크, 폴더 통합테스트작성

src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
- resolve #105 
- 폴더 세부 조회시 원본 폴더 정보 보기 복구
<br>
=> :bug:[BUG]폴더 세부 조회시 원본 폴더 정보 보기 복구

src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
- resolve #90 
- 태그, 루트태그 통합 테스트 수정
<br>
- request dto -> 직접 String 전달로 변경
<br>
=> [FEAT] 폴더 통합 테스트 수정

src/test/java/com/prgrms/team03linkbookbe/integration/user/UserIntegrationTest.java
- resolve #108 
- 유저 통합테스트 리퀘스트 헤더, 필드 추가
<br>
- 유저 통합테스트 리퀘스트 헤더, 필드 추가
<br>
=> [FEAT] 사용자 통합 테스트 수정

build.gradle
- resolve #{111}
RestDoc build.gradle 설정
<br>
=> [SETTING] RestDoc build.gradle 설정

src/docs/asciidoc/index.adoc, src/main/resources/static/docs/index.html
- resolve #{115}
RestDoc index.html 배포
<br>
=> [SETTING] RestDoc index.html 배포

src/test/java/com/prgrms/team03linkbookbe/integration/refreshtoken/RefreshTokenIntegrationTest.java
- resolve #117 
- 액세스 토큰 기간 늘림에 따라 테스트 코드 수정
<br>
- 액세스 토큰 기간 늘림에 따라 테스트 코드 수정
<br>
=> [BUG] 액세스 토큰 재발급 통합 테스트 수정

src/main/java/com/prgrms/team03linkbookbe/like/controller/LikeController.java, src/main/java/com/prgrms/team03linkbookbe/like/repository/LikeRepository.java, src/main/java/com/prgrms/team03linkbookbe/like/service/LikeService.java, src/test/java/com/prgrms/team03linkbookbe/integration/like/LikeIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/like/service/LikeServiceTest.java
- resolve #118 
- 좋아요 삭제 로직 변경
<br>
=> :recycle:좋아요 삭제 로직 변경

src/test/java/com/prgrms/team03linkbookbe/integration/comment/CommentIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/integration/like/LikeIntegrationTest.java
- resolve #121 
- 댓글, 좋아요 통합테스트 수정.
=> :recycle:댓글, 좋아요 통합테스트 수정

src/test/java/com/prgrms/team03linkbookbe/unit/folder/controller/FolderControllerUnitTest.java
- resolve #99 
- 폴더 컨트롤러 단위 테스트 작성
<br>
- 폴더 컨트롤러 단위 테스트 작성 
<br>
=> [FEAT] 폴더 컨트롤러 단위 테스트 작성

BOOT-INF/classes/static/docs/index.html, src/docs/asciidoc/index.adoc, src/main/java/com/prgrms/team03linkbookbe/bookmark/controller/BookmarkController.java, src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/PinnedListResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/PinnedResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java, src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java, src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
- resolve #124 
- 자기 자신 pinned 폴더 리스트 조회 api, 테스트, docs
<br>
- 자기 자신 pinned 폴더 리스트 조회 api, 테스트, docs
<br>
=> [FEAT] 자기 자신 pinned 폴더 리스트 조회

BOOT-INF/classes/static/docs/index.html, src/main/java/com/prgrms/team03linkbookbe/folder/dto/PinnedResponse.java, src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java, src/main/resources/static/docs/index.html, src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
- resolve #126
- pinned response 유저 dto 추가
<br>
- pinned response 유저 dto 추가
<br>
=> [FEAT] pinned response 유저 dto 추가

src/main/java/com/prgrms/team03linkbookbe/comment/service/CommentService.java, src/main/java/com/prgrms/team03linkbookbe/folder/dto/FolderDetailResponse.java, src/main/java/com/prgrms/team03linkbookbe/like/service/LikeService.java, src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
- resolve #128 
- 폴더 자세히 보기 댓글 출력 및 좋아요, 댓글 에러 출력 수정
=> :recycle:[REFACTOR]폴더 자세히 보기 댓글 출력 및 좋아요, 댓글 에러 출력 수정

src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java, src/main/java/com/prgrms/team03linkbookbe/rootTag/entity/RootTagCategory.java
- resolve #130 
- 루트 태그 전체 카테고리 조회 기능 추가
<br>
- 루트 태그 전체 카테고리 조회 기능 추가
<br>
=> [FEAT] 루트 태그 전체 카테고리 조회 기능 추가

src/main/java/com/prgrms/team03linkbookbe/folder/dto/CreateFolderRequest.java, src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java
- resolve #132 
- :bug: 폴더 생성 시 contents "" 오류 수정
<br>
- :bug: 폴더 생성 시 contents "" 오류 수정
<br>
=> :bug: 폴더 생성 시 contents "" 오류 수정

src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java, src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java, src/test/java/com/prgrms/team03linkbookbe/unit/folder/service/FolderServiceUnitTest.java
- resolve #134 
- 폴더 리스트 조회 시 isPrivate 확인 여부 수정
<br>
- isPrivate 값을 넘겨받지 않은 경우 isPrivate 여부에 상관없이 검색
<br>
=> :recycle:[REFACTOR] 폴더 리스트 조회 시 isPrivate 확인 여부 수정

src/main/java/com/prgrms/team03linkbookbe/folder/repository/FolderRepository.java
- resolve #136 
- 폴더 조회 쿼리 수정
<br>
- jpql에서 countQuery 수정
<br>
=> :recycle:폴더 조회 쿼리 수정

BOOT-INF/classes/static/docs/index.html, src/main/java/com/prgrms/team03linkbookbe/folder/dto/PinnedResponse.java, src/main/resources/static/docs/index.html, src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java
- resolve #138 
- pinned 폴더 response 수정
<br>
- pinned 폴더 response 수정
<br>
=> [REFACTOR] pinned 폴더 response 수정

src/main/java/com/prgrms/team03linkbookbe/folder/controller/FolderController.java, src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java, src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/folder/controller/FolderControllerUnitTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/folder/service/FolderServiceUnitTest.java
- resolve #140 
- 태그 검색 로직 수정
<br>
- 태그 검색시 body에 검색어를 담는 대신 queryString으로 변경
=> :recycle:[REFACTOR] 태그 검색 로직 수정

BOOT-INF/classes/static/docs/index.html, src/main/resources/static/docs/index.html
- resolve #140 
- 태그 검색 로직 수정 docs 업데이트
=> :recycle:[REFACTOR] 태그 검색 로직 수정 docs 업데이트

src/main/java/com/prgrms/team03linkbookbe/folder/dto/PinnedResponse.java
- resolve #143 
- isPinned, isPrivate 같게 나오는 오류 수정
<br>
- isPinned, isPrivate 같게 나오는 오류 수정
<br>
=> [BUG] isPinned, isPrivate 같게 나오는 오류 수정

src/main/java/com/prgrms/team03linkbookbe/jwt/exception/AccessTokenExpiredException.java
- resolve #{146}
- Access-Token exceptioncode 수정
<br>
=> [BUG] Access-Token exceptioncode 수정

README.md
- resolve #{148}
- Readme.md update
<br>
=> [SETTING] Readme.md update

README.md
- resolve #{150}
- Readme.md 이미지 수정
<br>
=> [SETTING] Readme.md 이미지 수정

src/main/java/com/prgrms/team03linkbookbe/rootTag/entity/RootTagCategory.java, src/main/java/com/prgrms/team03linkbookbe/tag/entity/TagCategory.java
- resolve #152 
- 서브태그 리스트 추가
- Tag Enum 필드 추가
<br>
- 서브태그 리스트 추가
- TagCategory(Enum) 파일 수정
- 추가한 필드는 RootTagCategory 파일에도 추가
- DB 에 값 추가
=> [FEAT] Tag Enum 필드 추가

src/main/java/com/prgrms/team03linkbookbe/interest/entity/SubTag.java
- resolve #155 
<br>
- 추가 또는 변경된 내용을 적어주세요. 
<br>
- 리뷰어가 참고할만한 사항이 있으면 적어주세요.                              
<br>
=> [BUG] 태그 관련 이슈

README.md
- resolve #{157}
- Readme.md 업데이트
<br>
=> [SETTING] Readme.md 업데이트

src/main/java/com/prgrms/team03linkbookbe/interest/entity/SubTag.java, src/main/java/com/prgrms/team03linkbookbe/interest/entity/TagGroup.java, src/test/java/com/prgrms/team03linkbookbe/integration/user/UserIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/interest/repository/InterestRepositoryTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/interest/service/InterestServiceTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/user/repository/UserRepositoryTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
- resolve #{167}
- Interest Enum 수정
<br>
=> [REFACTOR] Interest Enum 수정

src/main/java/com/prgrms/team03linkbookbe/like/entity/Like.java
- resolve #170 
- 좋아요한 폴더 삭제가 안되는 문제 발생
<br>
- 좋아요 엔티티에 cascade 옵션 추가
=> :bug:[BUG] 좋아요 폴더 연관관계 버그 수정

src/main/java/com/prgrms/team03linkbookbe/folder/entity/Folder.java, src/main/java/com/prgrms/team03linkbookbe/like/entity/Like.java
- resolve #170 
- 좋아요한 폴더 삭제가 안되는 문제 발생
<br>
- 좋아요 엔티티에 cascade 옵션 추가
=> :bug:좋아요 폴더 연관관계 버그 수정

BOOT-INF/classes/static/docs/index.html, src/main/java/com/prgrms/team03linkbookbe/common/exception/ExceptionCode.java, src/main/java/com/prgrms/team03linkbookbe/user/controller/UserController.java, src/main/java/com/prgrms/team03linkbookbe/user/controller/UserControllerAdvice.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/LoginRequestDto.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/RegisterRequestDto.java, src/main/java/com/prgrms/team03linkbookbe/user/dto/UserUpdateRequestDto.java, src/main/java/com/prgrms/team03linkbookbe/user/entity/User.java, src/main/java/com/prgrms/team03linkbookbe/user/exception/IllegalPasswordException.java, src/main/java/com/prgrms/team03linkbookbe/user/service/UserService.java, src/test/java/com/prgrms/team03linkbookbe/integration/user/UserIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/user/controller/UserControllerUnitTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/user/service/UserServiceTest.java
- resolve #169
- 유저 엔터티, dto 검증 추가
<br>
- 유저 엔터티, dto 검증 추가
<br>
=> [FEAT] 유저 엔터티, dto 검증 추가

src/main/java/com/prgrms/team03linkbookbe/bookmark/entity/Bookmark.java, src/main/java/com/prgrms/team03linkbookbe/bookmark/repository/BookmarkRepository.java, src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java, src/test/java/com/prgrms/team03linkbookbe/integration/folder/FolderIntegrationTest.java, src/test/java/com/prgrms/team03linkbookbe/unit/folder/service/FolderServiceUnitTest.java
- 폴더수정로직개선
<br>
- 폴더수정시 북마크 모두 삭제후 다시 생성 -> 기존북마크 update, 새로운북마크 추가, 없어진 북마크 삭제로 변경
- url 길이 넘는 경우에 대비해 TEXT로 변경
<br>
=> [REFACTOR] 폴더수정부분 버그수정 및 로직개선 

src/docs/asciidoc/index.adoc, src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
=> Refact/i177 폴더수정 버그 픽스

src/main/java/com/prgrms/team03linkbookbe/folder/service/FolderService.java
- 폴더수정 로직 버그 수정중
- <br>
- 기존과 dto id비교가 제대로 되지 않음 
<br>
=> 🐛폴더수정 로그추가

BOOT-INF/classes/static/docs/index.html, src/main/resources/static/docs/index.html
=> ✅폴더수정 API문서반영
